column_width = 120
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4

quote_style = "AutoPreferSingle"
call_parentheses = "NoSingleTable"
no_call_parentheses = true
collapse_simple_statement = "Never"
