column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4

quote_style = "AutoPreferSingle"
call_parentheses = "Always"
no_call_parentheses = false
collapse_simple_statement = "Never"
