return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = true,
	enabled = true,
	event = "UIEnter",
	config = function()
		require("catppuccin").setup({
			flavour = "latte",
			term_colors = true,
			no_italic = true,
			color_overrides = {
				latte = {
					base = "#FFFFFF",
					mantle = "#EFF1F5",
					crust = "#E6E9EF",
				},
				mocha = {
					rosewater = "#EA6962",
					flamingo = "#EA6962",
					pink = "#D3869B",
					mauve = "#D3869B",
					red = "#EA6962",
					maroon = "#EA6962",
					peach = "#BD6F3E",
					yellow = "#D8A657",
					green = "#A9B665",
					teal = "#89B482",
					sky = "#89B482",
					sapphire = "#89B482",
					blue = "#7DAEA3",
					lavender = "#7DAEA3",
					text = "#D4BE98",
					subtext1 = "#BDAE8B",
					subtext0 = "#A69372",
					overlay2 = "#8C7A58",
					overlay1 = "#735F3F",
					overlay0 = "#5A4525",
					surface2 = "#4B4F51",
					surface1 = "#2A2D2E",
					surface0 = "#232728",
					base = "#1D2021",
					mantle = "#191C1D",
					crust = "#151819",
				},
			},
			integrations = {
				cmp = true,
				gitsigns = true,
				notify = true,
				telescope = true,
				alpha = true,
				harpoon = true,
				mason = true,
				neotree = true,
				treesitter_context = true,
				which_key = true,
				illuminate = true,
			},
		})
		vim.cmd.colorscheme("catppuccin")
	end,
}
