return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = true,
	enabled = true,
	event = "UIEnter",
	config = function()
		require("catppuccin").setup({
			flavour = "mocha",
			term_colors = true,
			no_italic = true,
			color_overrides = {
				latte = {
					red = "#dc2626",
					peach = "#f97316",
					yellow = "#f59e0b",
					green = "#16a34a",
					teal = "#0d9488",
					sapphire = "#0891b2",
					sky = "#0284c7",
					blue = "#2563eb",
					lavender = "#4f46e5",
					mauve = "#7c3aed",
					maroon = "#9333ea",
					flamingo = "#c026d3",
					pink = "#db2777",
					rosewater = "#e11d48",
					text = "#0a0a0a",
					subtext1 = "#171717",
					subtext0 = "#262626",
					overlay2 = "#404040",
					overlay1 = "#525252",
					overlay0 = "#737373",
					surface2 = "#a3a3a3",
					surface1 = "#d4d4d4",
					surface0 = "#e5e5e5",
					base = "#ffffff",
					mantle = "#fafafa",
					crust = "#f5f5f5",
				},
				mocha = {
					red = "#ef4444",
					peach = "#fb923c",
					yellow = "#fbbf24",
					green = "#22c55e",
					teal = "#14b8a6",
					sapphire = "#06b6d4",
					sky = "#0ea5e9",
					blue = "#3b82f6",
					lavender = "#6366f1",
					mauve = "#8b5cf6",
					maroon = "#a855f7",
					flamingo = "#d946ef",
					pink = "#ec4899",
					rosewater = "#f43f5e",
					text = "#fafafa",
					subtext1 = "#f5f5f5",
					subtext0 = "#e5e5e5",
					overlay2 = "#d4d4d4",
					overlay1 = "#a3a3a3",
					overlay0 = "#737373",
					surface2 = "#525252",
					surface1 = "#404040",
					surface0 = "#262626",
					base = "#171717",
					mantle = "#0a0a0a",
					crust = "#000000",
				},
			},
			integrations = {
				cmp = true,
				gitsigns = true,
				notify = true,
				telescope = true,
				alpha = true,
				harpoon = true,
				mason = true,
				neotree = true,
				treesitter_context = true,
				which_key = true,
				illuminate = true,
				native_lsp = {
					enabled = true,
					virtual_text = {
						errors = { "italic" },
						hints = { "italic" },
						warnings = { "italic" },
						information = { "italic" },
					},
					underlines = {
						errors = { "underline" },
						hints = { "underline" },
						warnings = { "underline" },
						information = { "underline" },
					},
					inlay_hints = {
						background = true,
					},
				},
			},
		})
		vim.cmd.colorscheme("catppuccin")
	end,
}
