return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = true,
	enabled = false,
	event = "UIEnter",
	config = function()
		require("catppuccin").setup({
			flavour = "frappe",
			term_colors = true,
			no_italic = true,
			color_overrides = {
				latte = {
					text = "#0a0a0a",
					subtext1 = "#171717",
					subtext0 = "#262626",
					overlay2 = "#404040",
					overlay1 = "#525252",
					overlay0 = "#737373",
					surface2 = "#a3a3a3",
					surface1 = "#d4d4d4",
					surface0 = "#e5e5e5",
					base = "#ffffff",
					mantle = "#fafafa",
					crust = "#f5f5f5",
				},
				frappe = {
					text = "#fafafa",
					subtext1 = "#f5f5f5",
					subtext0 = "#e5e5e5",
					overlay2 = "#d4d4d4",
					overlay1 = "#a3a3a3",
					overlay0 = "#737373",
					surface2 = "#525252",
					surface1 = "#404040",
					surface0 = "#262626",
					base = "#171717",
					mantle = "#0a0a0a",
					crust = "#000000",
				},
			},
			integrations = {
				cmp = true,
				gitsigns = true,
				notify = true,
				telescope = true,
				alpha = true,
				harpoon = true,
				neotree = true,
				treesitter_context = true,
				which_key = true,
				illuminate = true,
				native_lsp = {
					enabled = true,
					virtual_text = {
						errors = { "italic" },
						hints = { "italic" },
						warnings = { "italic" },
						information = { "italic" },
					},
					underlines = {
						errors = { "underline" },
						hints = { "underline" },
						warnings = { "underline" },
						information = { "underline" },
					},
					inlay_hints = {
						background = true,
					},
				},
			},
		})
		vim.cmd.colorscheme("catppuccin")
	end,
}
